-- Adcash: Xem & Kiếm Thưởng
-- Schema currently deployed to Supabase project Bobbey.
-- All Adcash objects are namespaced with adcash_ to avoid touching orbit_leaderboard.

create table if not exists public.adcash_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance_vnd bigint not null default 0,
  lifetime_earned_vnd bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.adcash_reward_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'monlix',
  transaction_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_name text,
  reward_currency text,
  reward_value numeric not null default 0,
  reward_vnd bigint not null default 0,
  payout_usd numeric not null default 0,
  sub_id text,
  user_ip text,
  country_code text,
  status text not null check (status in ('valid','chargeback')),
  created_at timestamptz not null default now(),
  reversed_at timestamptz
);

create table if not exists public.adcash_withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  method text not null check (method in ('momo','bank')),
  destination text not null,
  amount_vnd bigint not null check (amount_vnd > 0),
  status text not null default 'pending' check (status in ('pending','paid','rejected')),
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists adcash_reward_events_user_created_idx
  on public.adcash_reward_events(user_id, created_at desc);
create index if not exists adcash_withdrawals_user_created_idx
  on public.adcash_withdrawals(user_id, created_at desc);

alter table public.adcash_wallets enable row level security;
alter table public.adcash_reward_events enable row level security;
alter table public.adcash_withdrawals enable row level security;

revoke all on public.adcash_wallets from anon, authenticated;
revoke all on public.adcash_reward_events from anon, authenticated;
revoke all on public.adcash_withdrawals from anon, authenticated;

grant select on public.adcash_wallets to authenticated;
grant select on public.adcash_reward_events to authenticated;
grant select on public.adcash_withdrawals to authenticated;

create policy "adcash users read own wallet"
on public.adcash_wallets for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "adcash users read own rewards"
on public.adcash_reward_events for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "adcash users read own withdrawals"
on public.adcash_withdrawals for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.adcash_apply_monlix_postback(
  p_transaction_id text,
  p_user_id uuid,
  p_task_name text,
  p_reward_currency text,
  p_reward_value numeric,
  p_payout_usd numeric,
  p_sub_id text,
  p_user_ip text,
  p_country_code text,
  p_status integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event public.adcash_reward_events%rowtype;
  v_reward_vnd bigint;
begin
  if p_transaction_id is null or length(trim(p_transaction_id)) = 0 then
    raise exception 'missing transaction id';
  end if;
  if not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'unknown user';
  end if;

  select * into v_event
  from public.adcash_reward_events
  where transaction_id = p_transaction_id
  for update;

  if p_status = 1 then
    if found then
      return jsonb_build_object('ok', true, 'duplicate', true, 'status', v_event.status, 'reward_vnd', v_event.reward_vnd);
    end if;

    v_reward_vnd := greatest(floor(coalesce(p_reward_value, 0)), 0)::bigint;

    insert into public.adcash_reward_events(
      transaction_id, user_id, task_name, reward_currency, reward_value,
      reward_vnd, payout_usd, sub_id, user_ip, country_code, status
    ) values (
      p_transaction_id, p_user_id, p_task_name, p_reward_currency, coalesce(p_reward_value, 0),
      v_reward_vnd, coalesce(p_payout_usd, 0), p_sub_id, p_user_ip, p_country_code, 'valid'
    );

    insert into public.adcash_wallets(user_id, balance_vnd, lifetime_earned_vnd, updated_at)
    values (p_user_id, v_reward_vnd, v_reward_vnd, now())
    on conflict (user_id) do update
      set balance_vnd = public.adcash_wallets.balance_vnd + excluded.balance_vnd,
          lifetime_earned_vnd = public.adcash_wallets.lifetime_earned_vnd + excluded.lifetime_earned_vnd,
          updated_at = now();

    return jsonb_build_object('ok', true, 'duplicate', false, 'status', 'valid', 'reward_vnd', v_reward_vnd);
  elsif p_status = 2 then
    if not found then
      return jsonb_build_object('ok', true, 'ignored', true, 'reason', 'missing_original');
    end if;
    if v_event.status = 'chargeback' then
      return jsonb_build_object('ok', true, 'duplicate', true, 'status', 'chargeback', 'reward_vnd', v_event.reward_vnd);
    end if;

    update public.adcash_reward_events
      set status = 'chargeback', reversed_at = now()
      where id = v_event.id;

    insert into public.adcash_wallets(user_id, balance_vnd, lifetime_earned_vnd, updated_at)
    values (p_user_id, -v_event.reward_vnd, 0, now())
    on conflict (user_id) do update
      set balance_vnd = public.adcash_wallets.balance_vnd - v_event.reward_vnd,
          updated_at = now();

    return jsonb_build_object('ok', true, 'duplicate', false, 'status', 'chargeback', 'reward_vnd', -v_event.reward_vnd);
  else
    raise exception 'unsupported status';
  end if;
end;
$$;

revoke all on function public.adcash_apply_monlix_postback(text, uuid, text, text, numeric, numeric, text, text, text, integer) from public, anon, authenticated;
grant execute on function public.adcash_apply_monlix_postback(text, uuid, text, text, numeric, numeric, text, text, text, integer) to service_role;

create or replace function public.adcash_request_withdrawal(
  p_method text,
  p_destination text,
  p_amount_vnd bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_balance bigint;
  v_id bigint;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if p_method not in ('momo','bank') then raise exception 'invalid method'; end if;
  if p_destination is null or length(trim(p_destination)) < 3 then raise exception 'invalid destination'; end if;
  if p_amount_vnd < 50000 then raise exception 'minimum withdrawal is 50000 VND'; end if;

  insert into public.adcash_wallets(user_id, balance_vnd, lifetime_earned_vnd, updated_at)
  values (v_user_id, 0, 0, now())
  on conflict (user_id) do nothing;

  select balance_vnd into v_balance
  from public.adcash_wallets
  where user_id = v_user_id
  for update;

  if v_balance < p_amount_vnd then raise exception 'insufficient balance'; end if;

  update public.adcash_wallets
  set balance_vnd = balance_vnd - p_amount_vnd, updated_at = now()
  where user_id = v_user_id;

  insert into public.adcash_withdrawals(user_id, method, destination, amount_vnd)
  values (v_user_id, p_method, trim(p_destination), p_amount_vnd)
  returning id into v_id;

  return jsonb_build_object('ok', true, 'withdrawal_id', v_id, 'balance_vnd', v_balance - p_amount_vnd);
end;
$$;

revoke all on function public.adcash_request_withdrawal(text, text, bigint) from public, anon;
grant execute on function public.adcash_request_withdrawal(text, text, bigint) to authenticated;
